
%dw 2.0
output application/java 
---
{
  event : {
    ChangeEventHeader : {
    },
    Name : "Clement",
    Type : "nisi",
    ParentId : "88dca2e3c26a411ab8d",
    BillingAddress : {
    },
    ShippingAddress : {
    },
    Phone : "(732)-549-3915",
    Fax : "(132)-670-6311",
    AccountNumber : "nisi",
    Website : "unde",
    Sic : "qui",
    Industry : "unde",
    AnnualRevenue : 38,
    NumberOfEmployees : 80,
    Ownership : "ipsam",
    TickerSymbol : "voluptatem",
    Description : "quia est ad sint veniam, proident, quia ",
    Rating : "dolore",
    Site : "explicabo.",
    NameLocal : "Amanda",
    OwnerId : "046979f3b5a5475abda",
    CreatedDate : 55,
    CreatedById : "b62b4a5ce7f942f0baa",
    LastModifiedDate : 68,
    LastModifiedById : "52cc5eb941214160b9e",
    Jigsaw : "aliquip",
    JigsawCompanyId : "dfe0f7379ad24315a6e",
    CleanStatus : "eius",
    AccountSource : "consectetur,",
    DunsNumber : "dicta",
    Tradestyle : "numquam",
    NaicsCode : "rem",
    NaicsDesc : "quae",
    YearStarted : "explicabo.",
    SicDesc : "sequi",
    DandbCompanyId : "98e3226cec1f4b5dbf7",
    OperatingHoursId : "915cd1438b664c85a68",
    CustomerPriority__c : "quia",
    SLA__c : "culpa",
    Active__c : "quae",
    NumberofLocations__c : 79,
    UpsellOpportunity__c : "fugiat",
    SLASerialNumber__c : "pariatur.",
    SLAExpirationDate__c : 80,
    External_Account_Id__c : "id",
    External_Customer_Id__c : "Duis",
  },
  replayId : 15,
  eventId : "fd5dc3de9e4d4ae1b77",
}
