
%dw 2.0
output application/java 
---
{
  event : {
    ChangeEventHeader : {
    },
    Name : "Adelina",
    Type : "omnis",
    ParentId : "bdc2510866cb4738b6d",
    BillingAddress : {
    },
    ShippingAddress : {
    },
    Phone : "(263)-152-8657",
    Fax : "(242)-118-4479",
    AccountNumber : "qui",
    Website : "nisi",
    Sic : "quis",
    Industry : "veniam,",
    AnnualRevenue : 27,
    NumberOfEmployees : 67,
    Ownership : "laboriosam,",
    TickerSymbol : "irure",
    Description : "nostrum ut natus sint ipsa in modi aspernatur quae ",
    Rating : "sint",
    Site : "laboriosam,",
    NameLocal : "Carrol",
    OwnerId : "28030b642eca4c5a8af",
    CreatedDate : 65,
    CreatedById : "afc26935891d47a4b4d",
    LastModifiedDate : 43,
    LastModifiedById : "162d95fcb188460b8e5",
    Jigsaw : "et",
    JigsawCompanyId : "f4818d81d1564f02be8",
    CleanStatus : "cillum",
    AccountSource : "laborum.",
    DunsNumber : "perspiciatis",
    Tradestyle : "inventore",
    NaicsCode : "vitae",
    NaicsDesc : "beatae",
    YearStarted : "amet,",
    SicDesc : "do",
    DandbCompanyId : "b379229b53cb47ae8f9",
    OperatingHoursId : "1c0ffec0ed904e78869",
    CustomerPriority__c : "aut",
    SLA__c : "in",
    Active__c : "Excepteur",
    NumberofLocations__c : 80,
    UpsellOpportunity__c : "vitae",
    SLASerialNumber__c : "ullam",
    SLAExpirationDate__c : 21,
    External_Account_Id__c : "qui",
    External_Customer_Id__c : "incididunt",
  },
  replayId : 82,
  eventId : "003716a407544ff7b52",
}
